### ISSUE TITLE
Backward compatible global TSconfig doesn't work

### ISSUE THREAD

**Issue by fishbone1** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#244]
The solution suggested [here](https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/UsingSetting/PageTSconfig.html#global-page-tsconfig-compatible-with-typo3-11-and-12) doesn't work for me:

```php
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

$versionInformation = GeneralUtility::makeInstance(Typo3Version::class);
// Only include page.tsconfig if TYPO3 version is below 12 so that it is not imported twice.
if ($versionInformation->getMajorVersion() < 12) {
   ExtensionManagementUtility::addPageTSConfig('
      "@import 'EXT:myexample/Configuration/page.tsconfig'"
   ');
}
```

Before `addPageTSConfig` is called I get an exception caused by line 3 (version information assignment)

```[Mon May 02 15:48:35.454703 2022] [proxy_fcgi:error] [pid 5911] [client 127.0.0.1:51932] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught LogicException: TYPO3\\CMS\\Core\\Cache\\CacheManager can not be injected/instantiated during ext_localconf.php loading. Use lazy loading instead. in /home/default/mysite/public/typo3/sysext/core/Classes/ServiceProvider.php:115
Stack trace:
#0 /home/default/mysite/var/cache/code/di/DependencyInjectionContainer_f20ac9260e6dd54040f800c5ba672a4cc1c3df5f.php(5797): TYPO3\\CMS\\Core\\ServiceProvider::getCacheManager()
#1 /home/default/mysite/vendor/symfony/dependency-injection/Container.php(239): DependencyInjectionContainer_f20ac9260e6dd54040f800c5ba672a4cc1c3df5f->getCacheManagerService()
#2 /home/default/mysite/vendor/symfony/dependency-injection/Container.php(219): Symfony\\Component\\DependencyInjection\\Container->make()
#3 /home/default/mysite/public/typo3/sysext/core/Classes/ServiceProvider.php(352): Symfony\\Component\\DependencyInjection\\Container->get()
#4 /home/default/mysite/var/cache/code/di/DependencyInjectionContainer_f20ac9260e6dd54040f800c5ba672a4cc1c
...', referer: http://mysite.wsl.local:1234/typo3/login?redirect=record_edit&redirectParams=edit%255Btt_content%255D%255B13%255D%3Dedit
```

Also there are unexpected quote characters in lines 6 and 8. Correct code:

```php
...
   ExtensionManagementUtility::addPageTSConfig(
      "@import 'EXT:myexample/Configuration/page.tsconfig'"
   );
...
```

**Comment by mbrodala** [comment]
What is the exception/error you get? We can only see the beginning of the stack trace here.

**Comment by mbrodala** [comment]
For the syntax fix I just proposed https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/245

**Comment by fishbone1** [comment]
The stack trace is not helpful here. The actual error is caused by missing `use` statements. I proposed #246 for that.
